#!/usr/bin/env bash
# Render a Markdown-authored report of this subject (currently the Architecture
# Vision) to PDF through pandoc and LuaLaTeX. The PDF is the build's own output
# and stays in the report's build/ directory; nothing is published elsewhere.
#
# Deliberately not a Makefile target. `render-report` is latexmk-specific and
# shares nothing with a pandoc invocation but its name; and this pipeline has
# real shell in it -- a diagram loop, file collection, a sort -- which in a
# recipe would mean another `@set -e; \` blob with $$ doubled on every variable.
# A script gets proper quoting for paths full of spaces and Cyrillic, real error
# messages, and shellcheck. It lives beside the reports it renders rather than
# in the repository's scripts/: it knows this subject's layout and nothing else
# in the workspace calls it.
set -euo pipefail

# Paths come from this script's own location, never $PWD: every entry point in
# this repository derives its paths from __file__ / $BASH_SOURCE.
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
subject="$(dirname "$here")"

usage() {
    cat <<'EOF'
Usage: scripts/render-md-report.sh [<report dir>]

  <report dir>  Directory holding meta.yaml, header.tex and content/.
                Defaults to this subject's vision/. The PDF is written to
                <report dir>/build/<report dir name>.pdf.
EOF
}

src=""
while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help)
            usage
            exit 0
            ;;
        -*)
            echo "unknown option: $1" >&2
            usage >&2
            exit 2
            ;;
        *)
            [ -z "$src" ] || { echo "only one report directory may be given" >&2; exit 2; }
            src="$1"
            shift
            ;;
    esac
done

# The subject holds exactly one Markdown-authored report today, so the default
# names it rather than routing through an .env setting nobody would change.
src="${src:-$subject/vision}"
src="${src%/}"
# A relative argument is relative to the caller's cwd, which is what a shell
# completion of a path produces.
src="$(cd "$src" && pwd)"

[ -d "$src/content" ] || { echo "no content/ directory in '$src'" >&2; exit 1; }
[ -f "$src/meta.yaml" ] || { echo "no meta.yaml in '$src'" >&2; exit 1; }
[ -f "$src/header.tex" ] || { echo "no header.tex in '$src'" >&2; exit 1; }

name="$(basename "$src")"
build="$src/build"
mkdir -p "$build"

# --- Diagrams ---------------------------------------------------------------
# PlantUML to SVG to PDF: vector all the way, so a diagram scales to the text
# width without resampling. PlantUML lays C4 and use-case diagrams out through
# graphviz, so `dot` has to be installed too. The PDFs are build output like the
# document itself and live beside it, in the one gitignored directory here.
shopt -s nullglob
puml=("$src"/diagrams/*.puml)
shopt -u nullglob
if [ ${#puml[@]} -gt 0 ]; then
    command -v plantuml >/dev/null || {
        echo "diagrams/ holds ${#puml[@]} .puml file(s) but plantuml is not installed" >&2
        echo "  sudo pacman -S plantuml graphviz" >&2
        exit 1
    }
    for f in "${puml[@]}"; do
        stem="$(basename "$f" .puml)"
        plantuml -tsvg -o "$build" "$f"
        rsvg-convert -f pdf -o "$build/$stem.pdf" "$build/$stem.svg"
        echo "diagram: $stem.pdf"
    done
fi

# --- Collect ----------------------------------------------------------------
# pandoc concatenates its inputs in argument order, so this sorted list *is* the
# document order. LC_ALL=C because glibc's en_US collation ignores punctuation:
# under it `01.1-x.md` sorts before `01-x.md`, which would silently print 3.1.1
# ahead of 3.1. The three-digit prefix scheme is immune to that on its own; the
# locale pin is the belt to its braces.
mapfile -t files < <(find "$src/content" -name '*.md' -type f | LC_ALL=C sort)
[ ${#files[@]} -gt 0 ] || { echo "no .md files under '$src/content'" >&2; exit 1; }
echo "collected ${#files[@]} markdown file(s)"

# --- Render -----------------------------------------------------------------
# \graphicspath rather than pandoc's --resource-path: the document references
# images by bare filename, and latexmk resolves them relative to its own working
# directory, where images/ is not on the graphics search path. Generated into
# build/ because the paths are derived here, not constants header.tex could
# carry.
cat >"$build/graphicspath.tex" <<EOF
% Generated by scripts/render-md-report.sh; edits here are overwritten.
\\graphicspath{{$src/images/}{$build/}}
EOF

# classoption=letterpaper is mandatory: geometry in header.tex sets the margins
# but takes the paper size from the class, and pandoc's default would otherwise
# apply. Letter is the Word template's own paper, which this document matches.
# --top-level-division=section keeps '#' off \chapter, which would otherwise
# print a stray "Chapter 1" above every top-level heading. --toc-depth is one
# more than the deepest heading wanted in the contents: pandoc subtracts the
# unused chapter level before writing \setcounter{tocdepth}, so 4 here is the
# document's three numbered levels.
pandoc "${files[@]}" \
    --from=markdown+mark \
    --metadata-file="$src/meta.yaml" \
    --filter pandoc-crossref \
    --lua-filter="$here/md-report-tables.lua" \
    --top-level-division=section \
    --toc --toc-depth=4 \
    --standalone \
    --to=latex \
    -V documentclass=extreport \
    -V classoption=11pt \
    -V classoption=letterpaper \
    -V colorlinks=true \
    -V linkcolor=black \
    -V urlcolor=blue \
    -H "$src/header.tex" \
    -H "$build/graphicspath.tex" \
    -o "$build/$name.tex"

# latexmk, not pandoc's own --pdf-engine: pandoc runs the engine a fixed number
# of times, while latexmk reruns until the .aux stops changing -- and this
# document's contents is already two pages, so one more section is all it takes
# to need a pass more. -lualatex for fontspec, as in the Makefile. Output is
# hidden unless the run fails; the log stays in build/ either way.
latexmk -lualatex -interaction=nonstopmode -halt-on-error -file-line-error \
    -outdir="$build" -jobname="$name" "$build/$name.tex" >"$build/latexmk.out" 2>&1 ||
    { cat "$build/latexmk.out" >&2; exit 1; }
echo "wrote $build/$name.pdf"

# Highlights are the progress meter over the template: the lecturer's yellow
# instruction notes plus the author's own ==…== placeholders. Zero means the
# document is genuinely finished, so a count beats any checklist kept by hand.
# Grid-table header rules are runs of '=', so the lines that draw a table have
# to come out before ==…== is counted or every table reads as dozens of
# unresolved highlights.
marks=$(grep -hv '^[+|]' "${files[@]}" | grep -o -e '{\.mark}' -e '==' | wc -l)
echo "unresolved highlights: $marks"
